apiVersion: apps/v1
kind: Deployment
metadata:
  name: emulador-dos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emulador-dos
  template:
    metadata:
      labels:
        app: emulador-dos
    spec:
      containers:
      - name: emulador-dos-container
        image: emulador-dos:latest
